
### getAll
GET {{URL}}

### getById
GET {{URL}}/2

### getBySpeciality
GET {{URL}}/speciality/PSYCHIATRY

### getByBirthDateRange
GET {{URL}}/birthdate-range/1970-01-01/1990-01-01

### createDoctor
POST {{URL}}
Content-Type: application/json

{
  "name": "CREATED DOCTOR",
  "dateOfBirth": "1978-09-12",
  "yearOfGraduation": 2003,
  "nameOfClinic": "Eastside Health Services",
  "speciality": "SURGERY"
}

### updateDoctor
PUT {{URL}}/13
Content-Type: application/json

{
  "name": "UPDATED DOCTOR",
  "dateOfBirth": "1999-12-10",
  "yearOfGraduation": 2024,
  "nameOfClinic": "Westside Health Services",
  "speciality": "PSYCHIATRY"
}

### deleteDoctor
DELETE {{URL}}/13
